### ISSUE TITLE
Typo Report | cogs/music.py

### ISSUE THREAD

**Issue by Adversing** [tonno7103/IBMusic#1]
`em.description = f"**{result.title}** \n" \
                                 f"Duation: **{convert(result.duration)}**\n" \
                                 f"Published by: **{result.author}**\n" \
                                 f"Url: {result.uri}"`

**duation** should be re-written as it is a typo.
Both errors are on **cogs/music.py** on line [287](https://github.com/tonno7103/IBMusic/blob/main/cogs/music.py#L287) and [301](https://github.com/tonno7103/IBMusic/blob/main/cogs/music.py#L301) respectively.

**Comment by tonno7103** [comment]
Fixed

**Comment by Adversing** [comment]
(uwu baka)
